name: Trigger auto deployment for python-test-wizerr

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/python-test-wizerr-AutoDeployTrigger-711e4317-d76e-43b2-97e1-5ccc72aa6a57.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          # client-id: ${{ secrets.PYTHONTESTWIZERR_AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.PYTHONTESTWIZERR_AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.PYTHONTESTWIZERR_AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.PYTHONTESTWIZERR_REGISTRY_USERNAME }}
          # Same as client Id
          registryPassword: ${{ secrets.PYTHONTESTWIZERR_REGISTRY_PASSWORD }}
          # Same as client Secret
          containerAppName: python-test-wizerr
          resourceGroup: wizerr-dev
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


